blog/urls.py
from django.urls import path
from .views import BlogListView, BlogDetailView

app_name = 'blog'
urlpatterns = [
    path('', BlogListView.as_view(), name='list'),
    path('<slug:slug>/', BlogDetailView.as_view(), name='detail'),
]

education/urls.py
from django.urls import path
from .views import EducationListView

app_name = 'education'
urlpatterns = [
    path('', EducationListView.as_view(), name='list'),
]

myblogdeploy/urls.py
from django.conf import settings
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from .views import IndexView


urlpatterns = [
    path('admin/', admin.site.urls),
    path('', IndexView.as_view(), name='index'),
    path('blog/', include('blog.urls', namespace='blog')),
    path('project/', include('project.urls', namespace='project')),
    path('education/', include('education.urls', namespace='education')),
]

if settings.DEBUG:
	urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
	urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

project/urls.py
from django.urls import path
from .views import ProjectListView, ProjectDetailView

app_name = 'project'
urlpatterns = [
    path('', ProjectListView.as_view(), name='list'),
    path('<slug:slug>/', ProjectDetailView.as_view(), name='detail'),
]

blog/models.py
from django.db import models
from django.urls import reverse
from django.utils.text import slugify


class Blog(models.Model):
	title = models.CharField(max_length=50)
	slug = models.SlugField(null=True, blank=True)
	pub_date = models.DateTimeField()
	body = models.TextField()
	height_field = models.IntegerField(default=0)
	width_field = models.IntegerField(default=0)
	cover = models.ImageField(null=True, blank=True, upload_to="images/", height_field="height_field",
							  width_field="width_field")

	def __str__(self):
		return self.title

	def get_absolute_url(self):
		return reverse('blog:detail', args=[str(self.slug)])

	def save(self, *args, **kwargs):
		if not self.id:
			# Newly created object, so set slug
			self.slug = slugify(self.title)
		super(Blog, self).save(*args, **kwargs)

education/models.py
from django.db import models
from django.urls import reverse


class Education(models.Model):
	title = models.CharField(max_length=50)
	category = models.CharField(max_length=50)
	start_date = models.DateField(null=True, blank=True)
	finish_date = models.DateField(null=True, blank=True)
	finished = models.BooleanField()
	institution = models.CharField(max_length=50)
	instructor = models.CharField(max_length=50, null=True, blank=True)
	url_address = models.URLField()

	def __str__(self):
		return self.title

project/models.py
from django.db import models
from django.urls import reverse
from django.utils.text import slugify


class Project(models.Model):
	title = models.CharField(max_length=50)
	slug = models.SlugField(null=True, blank=True)
	init_date = models.DateTimeField()
	body = models.TextField()
	height_field = models.IntegerField(default=0)
	width_field = models.IntegerField(default=0)
	cover = models.ImageField(null=True, blank=True, upload_to="images/project/", height_field="height_field",
							  width_field="width_field")

	def __str__(self):
		return self.title

	def get_absolute_url(self):
		return reverse('project:detail', args=[str(self.slug)])

	def save(self, *args, **kwargs):
		if not self.id:
			# Newly created object, so set slug
			self.slug = slugify(self.title)
		super(Project, self).save(*args, **kwargs)

blog/views.py
from django.views.generic import ListView, DetailView
from .models import Blog


class BlogListView(ListView):
    model = Blog
    template_name = "blog/blog_list.html"

    def get_context_data(self, **kwargs):
        # Call the base implementation first to get a context
        context = super().get_context_data(**kwargs)
        # Add in a QuerySet of all the books
        context['blog_list_reverse'] = Blog.objects.all().order_by("-pub_date")
        return context


class BlogDetailView(DetailView):
    model = Blog
    template_name = "blog/blog_detail.html"

education/views.py
from django.views.generic import ListView
from .models import Education


class EducationListView(ListView):
    model = Education
    template_name = "education/education_list.html"

    def get_context_data(self, **kwargs):
        # Call the base implementation first to get a context
        context = super().get_context_data(**kwargs)
        # Add in a QuerySet of all the books
        context['education_list_reverse'] = Education.objects.all().order_by("-finish_date")
        return context

myblogdeploy/views.py
from django.views.generic.base import TemplateView


class IndexView(TemplateView):
	template_name = 'index.html'

project/views.py
from django.views.generic import ListView, DetailView
from .models import Project


class ProjectListView(ListView):
    model = Project
    template_name = "project/project_list.html"

    def get_context_data(self, **kwargs):
        # Call the base implementation first to get a context
        context = super().get_context_data(**kwargs)
        # Add in a QuerySet of all the books
        context['project_list_reverse'] = Project.objects.all().order_by("-init_date")
        return context


class ProjectDetailView(DetailView):
    model = Project
    template_name = "project/project_detail.html"

templates/base.html
{% load static %}
<!doctype html>
<html lang="en">

<head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <!-- Bootstrap CSS -->
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/css/bootstrap.min.css" integrity="sha384-MCw98/SFnGE8fJT3GXwEOngsV7Zt27NXFoaoApmYm81iuXoPkFOJwJ8ERdknLPMO" crossorigin="anonymous">
    <!-- Font Awesome -->
    <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.4.1/css/all.css" integrity="sha384-5sAR7xN1Nv6T6+dT2mhtzEpVJvfS3NScPQTrOxhwjIuvcA67KV2R5Jz6kr4abQsz" crossorigin="anonymous">
    <!-- Custom Fonts -->
    <!-- Custom CSS -->
    <link rel="stylesheet" href="{% static 'css/mycustomstyle.css' %}?rand=7">
    <link rel="shortcut icon" href="{% static 'img/favicon.ico' %}" type="image/x-icon" />
    <title>
        {% block title %}Title{% endblock title %}
    </title>
</head>

<body>
    <!-- NAVIGATION -->
    {% include 'partials/_navbar.html' %}
    <!-- HEADER -->
    {% include 'partials/_header.html' %}
    <!-- CONTENT -->
    {% block content %}
    {% endblock content %}
    <!-- FOOTER -->
    {% include 'partials/_footer.html' %}
    <!-- Optional JavaScript -->
    <!-- jQuery first, then Popper.js, then Bootstrap JS -->
    <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.3/umd/popper.min.js" integrity="sha384-ZMP7rVo3mIykV+2+9J3UJ46jBk0WLaUAdn689aCwoqbBJiSnjAK/l8WvCWPIPm49" crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/js/bootstrap.min.js" integrity="sha384-ChfqqxuZUCnJSK3+MXmPNIyE6ZbWh2IMqE241rYiqJxyMiZ6OW/JmZQ5stwEULTy" crossorigin="anonymous"></script>
</body>

</html>

templates/blog/blog_detail.html
{% extends "base.html" %}
{% load static %}
{% block title %}
Blog
{% endblock title %}
<!-- CONTENT -->
{% block content %}
<!-- POST DETAIL -->
<section id="blog-detail-section" class="p-2">
  <div class="container">
    <div class="row">
      <div class="col-md-9 mx-auto">
        <img class="img-fluid" src="{{ blog.cover.url }}" alt="">
      </div>
    </div>
    <div class="row">
      <div class="col-md-9 mx-auto">
        <p>{{ blog.body }}</p>
      </div>
    </div>
  </div>
</section>
<!-- HEADER -->
<!-- HEADER -->
<!-- HEADER -->
{% endblock content %}

templates/blog/blog_list.html
{% extends "base.html" %}
{% load static %}
{% block title %}
Blog
{% endblock title %}
<!-- CONTENT -->
{% block content %}
<!-- lATEST POSTS -->
<section id="blog-list-section" class="p-2">
	<div class="container">
		{% for blog in blog_list_reverse %}
		<div class="row d-flex align-items-center pt-2">
			<div class="col-md-3">
				<img class="img-fluid rounded-circle" src="{{ blog.cover.url }}" alt="Image Not Found">
			</div>
			<div class="col-md-9">
				<h1><a href="{{ blog.get_absolute_url }}">{{ blog.title }}</a></h1>
				<p>{{ blog.body|truncatechars:300 }}</p>
				<p class="text-muted">Published: {{ blog.pub_date }}</p>
				<hr>
			</div>
		</div>
		{% endfor %}
	</div>
</section>
<!-- HEADER -->
<!-- HEADER -->
<!-- HEADER -->
{% endblock content %}

templates/education/education_list.html
{% extends "base.html" %}
{% load static %}
{% block title %}
Education
{% endblock title %}
<!-- CONTENT -->
{% block content %}
<!-- COURSES -->
<section id="education-list-section" class="p-2">
	<div class="container">
		<div class="row">
			<div class="card-columns mx-auto">
				{% for education in education_list_reverse %}
				{% if education.category == 'Data Science' %}
				<div class="card text-center bg-primary text-white">
					<div class="card-body">
						<a href="{{ education.url_address }}" target="_blank">
							<h5 class="card-title">{{ education.title }}</h5>
						</a>
						<p class="card-text font-italic">
							By {{ education.institution }}
						</p>
					</div>
					<div class="card-footer">
						<p class="card-text">
							{% if education.finished %}
							Completed In {{ education.finish_date|date:'M Y' }}
							{% else %}
							In progress
							{% endif %}
						</p>
					</div>
				</div>
				{% elif education.category == 'Web Development' %}
				<div class="card text-center bg-danger text-white">
					<div class="card-body">
						<a href="{{ education.url_address }}" target="_blank">
							<h5 class="card-title">{{ education.title }}</h5>
						</a>
						<p class="card-text font-italic">
							By {{ education.institution }}
						</p>
					</div>
					<div class="card-footer">
						<p class="card-text">
							{% if education.finished %}
							Completed In {{ education.finish_date|date:'M Y' }}
							{% else %}
							In progress
							{% endif %}
						</p>
					</div>
				</div>
				{% else %}
				<div class="card text-center bg-warning text-white">
					<div class="card-body">
						<a href="{{ education.url_address }}" target="_blank">
							<h5 class="card-title">{{ education.title }}</h5>
						</a>
						<p class="card-text font-italic">
							By {{ education.institution }}
						</p>
					</div>
					<div class="card-footer">
						<p class="card-text">
							{% if education.finished %}
							Completed In {{ education.finish_date|date:'M Y' }}
							{% else %}
							In progress
							{% endif %}
						</p>
					</div>
				</div>
				{% endif %}
				{% endfor %}
				<!-- SAMPLE CARDS FOR TEST -->
				<!-- {% for i in "x"|rjust:"20" %}
				<div class="card text-center bg-primary text-white">
					<div class="card-body">
						<a href="{{ education.url_address }}" target="_blank">
							<h5 class="card-title">{{ education.title }}</h5>
						</a>
						<p class="card-text font-italic">
							By {{ education.institution }}
						</p>
					</div>
					<div class="card-footer">
						<p class="card-text">
							{% if education.finished %}
							Completed In {{ education.finish_date|date:'M Y' }}
							{% else %}
							In progress
							{% endif %}
						</p>
					</div>
				</div>
				{% endfor %} -->
				<!-- END TEST -->
			</div>
		</div>
	</div>
</section>
{% endblock content %}

templates/index.html
{% extends "base.html" %}
{% load static %}
{% block title %}
Home
{% endblock title %}
<!-- CONTENT -->
{% block content %}
<!-- PHOTO SECTION -->
<section id="photo-section" class="p-2">
	<div class="container">
		<div class="row align-items-center">
			<div class="col-md-6">
				<img class="img-fluid rounded" src="{% static 'img/me.jpg' %}" alt="Image not found">
			</div>
			<div class="col-md-6 text-center">
				<h1>I'm Jay</h1>
				<p class="lead">Lorem ipsum dolor sit amet, consectetur adipisicing elit. Laboriosam, optio!</p>
			</div>
		</div>
	</div>
	<div class="container">
		<div class="row">
			<div class="col">
				<p>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Dicta quasi fugiat, quia iste quam exercitationem
					cumque aspernatur debitis natus cupiditate iure, error eveniet dolorum facilis repudiandae aperiam perspiciatis
					aliquid delectus odio. Tempora possimus, fuga rem distinctio veritatis perspiciatis numquam autem voluptatem.
					Accusamus exercitationem vitae saepe? Nemo reprehenderit eos aperiam eligendi.</p>
				<p>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Dicta quasi fugiat, quia iste quam exercitationem
					cumque aspernatur debitis natus cupiditate iure, error eveniet dolorum facilis repudiandae aperiam perspiciatis
					aliquid delectus odio. Tempora possimus, fuga rem distinctio veritatis perspiciatis numquam autem voluptatem.
					Accusamus exercitationem vitae saepe? Nemo reprehenderit eos aperiam eligendi.</p>
			</div>
		</div>
	</div>
</section>
{% endblock content %}

templates/partials/_footer.html
<footer id="footer" class="bg-dark text-white text-center px-2 py-4 mt-4">
  <div class="container">
    <div class="row">
      <div class="col-md-6 text-left">
        <p>About This Page</p>
        <p class="text-muted">
          This website was coded in HTML, CSS, and Django with the help of Bootstrap. It is hosted on a LAMP server
          from DigitalOcean. The code can be found <a href="#"> here</a>.
        </p>
      </div>
      <div class="col-md-3 text-left">
        <p>Sitemap</p>
        <p class="text-muted">
          Home <br>
          Education <br>
          Project <br>
          Blog <br>
        </p>
      </div>
      <div class="col-md-3 text-left">
        <p>Connect</p>
        <i class="fab fa-twitter fa-2x mx-2"></i>
        <i class="fab fa-facebook fa-2x mx-2"></i>
        <i class="fab fa-github fa-2x mx-2"></i>
        <i class="fab fa-instagram fa-2x mx-2"></i>
        <i class="fab fa-linkedin fa-2x mx-2"></i>
      </div>
    </div>
    <div class="row">
      <div class="col text-center">
        <hr class="bg-light">
        Copyright &copy; {% now "Y" %} Jay Choi
      </div>
    </div>
  </div>
</footer>

templates/partials/_header.html
{% if '/' == request.path %}
<header id="home-header" class="d-flex align-items-center bg-primary mb-4" style="height: 250px;">
  <div class="container">
    <div class="row">
      <div class="col-md-6 m-auto text-center text-white">
        <h1>
          About Me
        </h1>
      </div>
    </div>
  </div>
</header>
{% elif 'education' in request.path %}
<header id="education-header" class="d-flex align-items-center bg-success mb-4" style="height: 250px;">
  <div class="container">
    <div class="row">
      <div class="col-md-6 m-auto text-center text-white">
        <h1>
          Education
        </h1>
      </div>
    </div>
  </div>
</header>
{% elif 'project' in request.path %}
<header id="project-header" class="d-flex align-items-center bg-warning mb-4" style="height: 250px;">
  <div class="container">
    <div class="row">
      <div class="col-md-6 m-auto text-center text-white">
        <h1>
          Project
        </h1>
      </div>
    </div>
  </div>
</header>
{% else%}
<header id="blog-header" class="d-flex align-items-center bg-info mb-4" style="height: 250px;">
  <div class="container">
    <div class="row">
      <div class="col-md-6 m-auto text-center text-white">
        <h1>
          Blog
        </h1>
      </div>
    </div>
  </div>
</header>
{% endif %}

templates/partials/_navbar.html
{% load static %}
<nav class="navbar navbar-expand-md navbar-dark bg-dark" id="home-nav">
  <div class="container">
    <a class="navbar-brand" href="{% url 'index' %}">
      <img class="mr-2" src="{% static 'img/favicon.ico' %}" width="30" height="30" alt="">
      Jay Choi
    </a>
    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNavDropdown" aria-controls="navbarNavDropdown"
      aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarNavDropdown">
      <ul class="navbar-nav ml-auto">
        <li
          {% if '/' == request.path %}
          class="nav-item ml-2 active"
          {% else %}
          class="nav-item ml-2"
          {% endif %}
        >
          <a class="nav-link" href="{% url 'index' %}">Home</span></a>
        </li>

        <li
          {% if 'education' in request.path %}
          class="nav-item ml-2 active"
          {% else %}
          class="nav-item ml-2"
          {% endif %}
        >
          <a class="nav-link" href="{% url 'education:list' %}">Education</a>
        </li>
        <li
          {% if 'project' in request.path %}
          class="nav-item ml-2 active"
          {% else %}
          class="nav-item ml-2"
          {% endif %}
        >
          <a class="nav-link" href="{% url 'project:list' %}">Project</a>
        </li>
        <li
          {% if 'blog' in request.path %}
          class="nav-item ml-2 active"
          {% else %}
          class="nav-item ml-2"
          {% endif %}
        >
          <a class="nav-link" href="{% url 'blog:list' %}">Blog</a>
        </li>
        <li class="nav-item dropdown ml-2">
          <a class="nav-link dropdown-toggle" href="#" id="navbarDropdownMenuLink" role="button" data-toggle="dropdown"
            aria-haspopup="true" aria-expanded="false">
            Connect
          </a>
          <div class="dropdown-menu" aria-labelledby="navbarDropdownMenuLink">
            <a class="dropdown-item" href="https://www.linkedin.com/in/hyukjae-jay-choi-2a857b160/" target="_blank">LinkedIn</a>
            <a class="dropdown-item" href="https://github.com/JayHChoi" target="_blank">GitHub</a>
            <a class="dropdown-item" href="{% static " txt/resume.pdf" %}" target="_blank">Resume</a>
          </div>
        </li>
      </ul>
    </div>
  </div>
</nav>

templates/project/project_detail.html
{% extends "base.html" %}
{% load static %}
{% block title %}
Project
{% endblock title %}
<!-- CONTENT -->
{% block content %}
<!-- PROJECT DETAIL -->
<section id="project-detail-section" class="p-2">
	<div class="container">
		<div class="row">
			<div class="col-md-9 mx-auto">
				<img class="img-fluid" src="{{ project.cover.url }}" alt="">
			</div>
		</div>
		<div class="row">
			<div class="col-md-9 mx-auto">
				<p>{{ project.body }}</p>
			</div>
		</div>
	</div>
</section>
<!-- HEADER -->
<!-- HEADER -->
<!-- HEADER -->
{% endblock content %}

templates/project/project_list.html
{% extends "base.html" %}
{% load static %}
{% block title %}
Project
{% endblock title %}
<!-- CONTENT -->
{% block content %}
<!-- lATEST POSTS -->
<section id="project-list-section" class="p-2">
    <div class="container">
        {% for project in project_list_reverse %}
        <div class="row pt-3 d-flex align-items-center">
            <div class="col-md-3">
                <img class="img-fluid rounded-circle" src="{{ project.cover.url }}" alt="Image Not Found">
            </div>
                <div class="col-md-9">
                    <h1><a href="{{ project.get_absolute_url }}">{{ project.title }}</a></h1>
                    <p>{{ project.body|truncatechars:300 }}</p>
                    <p class="text-muted">Initiated: {{ project.init_date }}</p>
                    <hr>
                </div>
            </div>
            {% endfor %}
        </div>
</section>
<!-- HEADER -->
<!-- HEADER -->
<!-- HEADER -->
{% endblock content %}